### ISSUE TITLE
some questiones about train

### ISSUE THREAD

**Issue by gshhher** [VITA-Group/LightGaussian#44]
Dear Author,

I am a beginner and would like to ask you a few questions. 
I have downloaded the NeRF360 dataset, but I’m not sure how to start training. When I follow the instructions and run "bash scripts/run_prune_finetune.sh", I am unable to proceed, even after adding the path to the "bicycle" dataset. Could you please provide a detailed explanation of the specific steps I should take?

Thank you!

**Comment by gshhher** [comment]
(lightgaussian):~/LightGaussian$ python train_densify_prune.py -s /mnt/data2/gsh/bicycle
Optimizing
Output folder: ./output/741c9e3a-8 [31/12 12:43:19]
Tensorboard not available: not logging progress [31/12 12:43:19]
/mnt/data2/gsh/bicycle [31/12 12:43:19]
Reading camera 1/194Traceback (most recent call last):
  File "/home/gsh/LightGaussian/train_densify_prune.py", line 268, in <module>
    training(
  File "/home/gsh/LightGaussian/train_densify_prune.py", line 57, in training
    scene = Scene(dataset, gaussians)
  File "/home/gsh/LightGaussian/scene/__init__.py", line 55, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](
  File "/home/gsh/LightGaussian/scene/dataset_readers.py", line 179, in readColmapSceneInfo
    cam_infos_unsorted = readColmapCameras(
  File "/home/gsh/LightGaussian/scene/dataset_readers.py", line 112, in readColmapCameras
    image = Image.open(image_path)
  File "/home/gsh/anaconda3/envs/lightgaussian/lib/python3.9/site-packages/PIL/Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/mnt/data2/gsh/bicycle/images/_DSC8679.JPG'
